name: template-api CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  AWS_BACK_TO_FRONT_URL : "http://localhost:4566/000000000000/BackToFront"
  AWS_FRONT_TO_BACK_URL : "http://localhost:4566/000000000000/FrontToBack"
  AWS_REGION : "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    
      - name: Start LocalStack
        run: |
          pip install localstack awscli-local[ver1] 
          docker pull localstack/localstack         
          localstack start -d                       
          echo "Waiting for LocalStack startup..." 
          localstack wait -t 30                     
          echo "Startup complete"          
      - name: Create Test Queues
        run: |                 
          awslocal sqs create-queue --queue-name FrontToBack --region $AWS_REGION
          awslocal sqs create-queue --queue-name BackToFront --region $AWS_REGION
          awslocal sqs list-queues
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build
        run: |
          npm run lint
          npm run format
          npm run build
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./coverage/lcov.info
          minimum-coverage: 50
          github-token: ${{ secrets.GITHUB_TOKEN }}
