name: CI
on: [push]
env:
  AWS_BACK_TO_FRONT_URL : "http://localhost:4566/000000000000/BackToFront"
  AWS_FRONT_TO_BACK_URL : "http://localhost:4566/000000000000/FrontToBack"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Start LocalStack
        run: |
          pip install localstack awscli-local[ver1] 
          docker pull localstack/localstack         
          localstack start -d                       
          echo "Waiting for LocalStack startup..." 
          localstack wait -t 30                     
          echo "Startup complete"          
      - name: Create Test Queues
        run: |                 
          awslocal sqs create-queue --queue-name FrontToBack
          awslocal sqs create-queue --queue-name BackToFront
          awslocal sqs list-queues

      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test:w

      - name: run format
        uses: borales/actions-yarn@v4
        with:
          cmd: format