name: main
on:
  # Should only be on push or pull request to main.
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create build folder
        run: npm run build

      - name: Store build folder as artifact for deploy
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  vite:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Testing
        run: npm run test:w
