name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: Set Node.js 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test:w # will run `yarn test` command
      - name: Format the app
        uses: borales/actions-yarn@v4
        with:
          cmd: format
    